name: Test iOS App

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/app/**'

jobs:
  test:
    name: Build and Test
    runs-on: macos-14
    timeout-minutes: 30
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
      
    - name: Show Xcode Version
      run: xcodebuild -version
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          packages/app/AWSCostMonitor/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
      
    - name: Clean Derived Data
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData
        rm -rf packages/app/AWSCostMonitor/DerivedData
        rm -rf packages/app/AWSCostMonitor/build
    
    - name: Build App
      timeout-minutes: 20
      run: |
        cd packages/app/AWSCostMonitor
        xcodebuild -project AWSCostMonitor.xcodeproj \
                   -scheme AWSCostMonitor \
                   -destination 'platform=macOS' \
                   -configuration Debug \
                   -allowProvisioningUpdates \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   DEVELOPMENT_TEAM="" \
                   -derivedDataPath ./DerivedData \
                   clean build
    
    - name: Run Tests
      timeout-minutes: 10
      run: |
        cd packages/app/AWSCostMonitor
        xcodebuild -project AWSCostMonitor.xcodeproj \
                   -scheme AWSCostMonitor \
                   -destination 'platform=macOS' \
                   -configuration Debug \
                   -allowProvisioningUpdates \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   DEVELOPMENT_TEAM="" \
                   -derivedDataPath ./DerivedData \
                   test