name: Test iOS App

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/app/**'

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
      
    - name: Show Xcode Version
      run: xcodebuild -version
      
    - name: Build App
      run: |
        cd packages/app/AWSCostMonitor
        xcodebuild -project AWSCostMonitor.xcodeproj \
                   -scheme AWSCostMonitor \
                   -destination 'platform=macOS' \
                   -configuration Debug \
                   -allowProvisioningUpdates \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   DEVELOPMENT_TEAM="" \
                   clean build
    
    - name: Run Tests
      run: |
        cd packages/app/AWSCostMonitor
        xcodebuild -project AWSCostMonitor.xcodeproj \
                   -scheme AWSCostMonitor \
                   -destination 'platform=macOS' \
                   -configuration Debug \
                   -allowProvisioningUpdates \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   DEVELOPMENT_TEAM="" \
                   test